### ISSUE TITLE
Problema rimanda a "Google Learning Center"

### ISSUE THREAD

**Issue by davideredigital** [corbindavenport/mini-google-tasks#10]
**"Google Learning Center
 Keep track of tasks"**

Salve, il plugin carica sempre questo link:
https://gsuite.google.com/learning-center/products/apps/keep-track-of-tasks/#!/section-1-1

Ho provato ad eseguire l'accesso e ad uscire, a riavviare Brave (Chromium Broswer) e a riavviare il pc. Il problema non cambia. Lo stesso problema lo hanno altri plugin di Google Tasks che invece pochi giorni fa funzionavano correttamente.
Spero possiate risolvere presto, avrei bisogno di poter usufruire di Tasks da Chrome.
Buon lavoro.

Davide

**Comment by corbindavenport** [comment]
Looks like Google shut down the Gmail Tasks widget the extension used. Looks like that's the end of Mini Google Tasks.
